version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: learnova-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learnova
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: learnova-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:3001
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: learnova-server
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=learnova
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - postgres

volumes:
  postgres_data: